version = 1

[[analyzers]]
name = "javascript"
environment = ["jquery"]
enabled = true
[analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "php"
enabled = true