version: '3'

services:

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:lcc-db}
      
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:lccpw}
      POSTGRES_USER: ${POSTGRES_USER:lccuser}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      
volumes:
  db-data:
