version: '3.7'
services:
    database:
        image: 'postgres:13-alpine'
        environment:
            POSTGRES_PASSWORD: lccpwd
            POSTGRES_USER: lccuser
            POSTGRES_DB: lcc-db
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '5432:5432'
        networks:
            - postgres
        volumes:
            - db-data:/var/lib/postgresql/data:rw

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - database
        environment:
            PGADMIN_DEFAULT_EMAIL: 'lcc@pgadmin.org'
            PGADMIN_DEFAULT_PASSWORD: 'lccpwd'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin

        ports:
            - '8080:80'
        networks:
            - postgres

networks:
    postgres:
        driver: bridge

volumes:
    db-data:
    pgadmin:
